print("Welcome to the tip calculator!")
total_bill = input("What was the total bill?")
tip_percentage = input("What percent tip will you be giving? 10,12 or 15? ")
split_num =  input("How many people will be splitting the bill? ")
int_split = int(split_num)
int_tip = int(tip_percentage)
int_bill = int(total_bill)
bill_after_tip = (int_bill + ((int_tip/int_bill)*100))
print(bill_after_tip)
total_split = (bill_after_tip/int_split)
print(int(total_split))